### ISSUE TITLE
Cannot preload resource path

### ISSUE THREAD

**Issue by GorEldeen** [gilzoide/godot-lua-pluginscript-distribution#1]
Hello hello!

I installed your plugin on Godot 3.6 beta 6

and I had this issue

```
Godot Engine v3.6.beta5.official (c) 2007-2022 Juan Linietsky, Ariel Manzur & Godot Contributors.
--- GDScript language server started on port 6008 ---
 editor/plugins/asset_library_editor_plugin.cpp:851 - Error getting image file from URL: https://raw.githubusercontent.com/BasilYes/godot-yandex-games-sdk/main/icon/icon.png
 editor/plugins/asset_library_editor_plugin.cpp:851 - Error getting image file from URL: https://raw.githubusercontent.com/arcweave/arcweave-godot-plugin/main/icon.png
 editor/plugins/asset_library_editor_plugin.cpp:851 - Error getting image file from URL: https://raw.githubusercontent.com/AnidemDex/Godot-DialogPlugin/main/icon.png
 editor/plugins/asset_library_editor_plugin.cpp:851 - Error getting image file from URL: https://raw.githubusercontent.com/AnidemDex/Godot-DialogPlugin/main/icon.png
Set default_project_path
Set code_complete_delay
Set add_type_hints
Set use_single_quotes
 No loader found for resource: res://addons/godot-lua-pluginscript/plugin/lua_repl.lua.
 No loader found for resource: res://addons/godot-lua-pluginscript/plugin/lua_repl.lua.
 scene/resources/resource_format_text.cpp:157 - Couldn't load external resource: res://addons/godot-lua-pluginscript/plugin/lua_repl.lua
 No loader found for resource: res://addons/godot-lua-pluginscript/plugin/export_plugin.lua.
 res://addons/godot-lua-pluginscript/plugin/plugin.gd:33 - Parse Error: Can't preload resource at path: res://addons/godot-lua-pluginscript/plugin/export_plugin.lua
 core/project_settings.cpp:239 - Property not found: editor_plugins/enabled
 No loader found for resource: res://addons/godot-lua-pluginscript/plugin/lua_repl.lua.
 No loader found for resource: res://addons/godot-lua-pluginscript/plugin/lua_repl.lua.
 scene/resources/resource_format_text.cpp:157 - Couldn't load external resource: res://addons/godot-lua-pluginscript/plugin/lua_repl.lua
 No loader found for resource: res://addons/godot-lua-pluginscript/plugin/export_plugin.lua.
 res://addons/godot-lua-pluginscript/plugin/plugin.gd:33 - Parse Error: Can't preload resource at path: res://addons/godot-lua-pluginscript/plugin/export_plugin.lua
 No loader found for resource: res://addons/godot-lua-pluginscript/plugin/lua_repl.lua.
 No loader found for resource: res://addons/godot-lua-pluginscript/plugin/lua_repl.lua.
 scene/resources/resource_format_text.cpp:157 - Couldn't load external resource: res://addons/godot-lua-pluginscript/plugin/lua_repl.lua
 No loader found for resource: res://addons/godot-lua-pluginscript/plugin/export_plugin.lua.
 res://addons/godot-lua-pluginscript/plugin/plugin.gd:33 - Parse Error: Can't preload resource at path: res://addons/godot-lua-pluginscript/plugin/export_plugin.lua
 No loader found for resource: res://addons/godot-lua-pluginscript/plugin/lua_repl.lua.
 No loader found for resource: res://addons/godot-lua-pluginscript/plugin/lua_repl.lua.
 scene/resources/resource_format_text.cpp:157 - Couldn't load external resource: res://addons/godot-lua-pluginscript/plugin/lua_repl.lua
 No loader found for resource: res://addons/godot-lua-pluginscript/plugin/export_plugin.lua.

```

![image](https://github.com/gilzoide/godot-lua-pluginscript-distribution/assets/112822849/e97c7117-b8db-42fd-909f-d61a9f776487)

it seems like for some reason, Godot cannot detect the lua files

![image](https://github.com/gilzoide/godot-lua-pluginscript-distribution/assets/112822849/be5f0e27-5af2-4270-903c-4282534d88ca)

**Comment by gilzoide** [comment]
Hey @GorEldeen, thanks for the report.
Hmm, for .lua files be unknown to Godot, the editor likely couldn't load the GDNative library correctly.
Are there any "dlopen" error messages in the Output tab?

Are you by any chance using macOS? The .dylib is not codesigned, so it won't work in editor/builds unless you codesign it yourself or manually try to open it with a double click from Finder and permit the loading of the unsigned library.

Or maybe you're using a platform/architecture that isn't built into the .gdnlib. Windows or Linux with ARM, maybe?

**Comment by GorEldeen** [comment]
Thanks for replying mate! And sorry I should have mentioned my OS, I'm using Linux with Linux Mint 21.3 Cinnamon 

Although, I had this problem on every other OS I ever used, but just now as I wanted to check on the plugin, hell I just restarted Godot and it worked like a charm, you should probably mention this on the assets store so others won't run in the same problem as me lol! thanks again mate!

**Comment by gilzoide** [comment]
> I just restarted Godot and it worked like a charm

Oh, ok! That is great xD

> you should probably mention this on the assets store so others won't run in the same problem as me lol! thanks again mate!

You mean, add a line like "after installing the plugin, restart Godot" or something like that? I think it makes sense.

**Comment by GorEldeen** [comment]
Yeah, I had 2 friends who also got stuck like that, I just told them about it and their mind was blown, anyways an awesome plugin you've made! I really needed something that's kind of easy as GDScript but also blazing fast, thanks for your awesome work Gil!
